name: PlatformIO CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        example: [examples/WakeOnLan-ESP32/WakeOnLan-ESP32.ino, examples/WakeOnLan-ESP8266/WakeOnLan-ESP8266.ino, examples/WakeOnLan-ESP32-Ethernet/WakeOnLan-ESP32-Ethernet.ino]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build examples
        run: pio ci --board=esp32dev --board=nodemcuv2 --board=esp32dev
        env:
          PLATFORMIO_CI_SRC: ${{ matrix.example }}
